### ISSUE TITLE
QSE : créer caractéristique -> transférer les habilitation

### ISSUE THREAD

**Issue by killiankopp** [pebble-solutions/App-QSE-habilitation#1]
**customer and user**
Groupe - admin

**Scrum brief**
En tant que QSE je veux pouvoir créer des caractéristiques afin de commencer à tester le transfert des habilitations vers une fonctionnalité dédiée

**Brief**
Les habilitations sont en fait des types de document. Cela pose de nombreux problèmes. Après réflexion, nous avons décidé de créer une table "caractéristiques" et une autre de liaison entre le personnel et ces caractéristiques pour remplacer le comportement des habilitations. Cette fonctionnalité vise à étendre les possibilités en ajoutant les habilitations mais aussi dans le même temps n'importe quelle caractéristique à un personnel.

Ressources RH type utilise les habilitations (qui seront converties en caractéristiques) il faudra aussi faire migrer ces données.

**Additional information**
Add any other context or screenshots about the issue here.

**Roles**
- design team :  
- dev team : 

**Code indication**

**Todo**
- [ ] @ :

**Comment by killiankopp** [comment]
test Killian

**Comment by killiankopp** [comment]
Ajouter dans la configuration de App-QSE-controle une variable permettant de déterminer le ou les IDS des caractéristiques étant à prendre en compte dans l'affichage de l'app (mkg_characteristic__type.id)

- [ ] @Guillaume35 ajouter la variable

**Comment by heligonSeb** [comment]
j'ai des question @killiankopp , @killiankopp.
 + vert: ce ne sont pas des clefs étrangères ?
 + rouge:  valeur en jour ? pour donner plus d'info dans la description
 + cyan: int de quoi ? autre table ? j'ai aucune idée de la valeur des champs

![image](https://user-images.githubusercontent.com/52566459/229521197-450f57a3-824c-414c-bfed-6c69b0521001.png)

**Comment by heligonSeb** [comment]
+ rouge: On prend le personnel_id comme $table_label ?
+ ici aussi on met des datetime pour les Date ?

![image](https://user-images.githubusercontent.com/52566459/229528121-c7db1e20-36e6-4fc9-9a28-b8e8f49b5f42.png)

**Comment by heligonSeb** [comment]
Utilisé `label` au lieu de `type` comme dans contrat_type ? histoire de garde un cohérence

![image](https://user-images.githubusercontent.com/52566459/229530730-e4ddecd0-f9f3-4c04-b380-16b7166be809.png)

**Comment by heligonSeb** [comment]
question @killiankopp @Guillaume35 :
Vu qu'on a plusieurs table type (contrat_type, document_type ...) mettre characteristic_type au lieu de juste type ou on part de principe si il y a que type_id ça prend un compte le type de la table actuelle ?

**Comment by heligonSeb** [comment]
- [ ] UML : @heligonSeb

**Comment by heligonSeb** [comment]
> * [x]  UML : @heligonSeb

je reviendrais sur diagramme de classe quand je vais avoir trouver un moyen de le rendre lisible

**Comment by heligonSeb** [comment]
ne pas faire des noms de champs avec des - exemple app-qse-control

**Comment by heligonSeb** [comment]
je ne peux pas faire la FK de roles vu que la table n'existe pas encore

**Comment by Guillaume35** [comment]
https://www.pebble.support/51/creer-des-api

**Comment by Guillaume35** [comment]
https://docs.google.com/document/d/1_OYMxvi453sCOBn7ZmJpuOlIOFlf8rnOxH8DlJiEBYI/edit

**Comment by killiankopp** [comment]
Les habilitations sont transférables via des moulinettes dans DVP. Il faut maintenant revoir les différents endroits où les habilitations sont utilisés et déterminer une date de transfert précise pour couper les services de l'ancien système et basculer sur le nouveau.
