### ISSUE TITLE
afficher les bouclages et les KNde KN en système SAMI

### ISSUE THREAD

**Issue by killiankopp** [pebble-solutions/App-QSE-habilitation#15]

**Comment by Guillaume35** [comment]
<img width="1755" alt="bouclage" src="https://github.com/pebble-solutions/App-QSE-habilitation/assets/945411/9ea22ee7-a000-41be-99a6-f66f8b33e07d">

**Comment by TigrouForMatic** [comment]
Es ce que cette issue ne serait pas consacrer a l'application kn ? @killiankopp @Guillaume35
