### ISSUE TITLE
Gérer un type d’habilitation

### ISSUE THREAD

**Issue by TigrouForMatic** [pebble-solutions/App-QSE-habilitation#22]
**Lister les types d’habilitations**

- [x] Afficher sous forme de liste les labels des types d’habilitation

Données a afficher : 
 - Nom (label)
 - Date de début (dd)
 - Date de fin (df)
 - Durée en jour (duree)
 
Autres données à prévoir :
 - Lien vers ID procédure (Boutons vers la procédure associé au type d'habilitation)

**Pouvoir créer un type d’habilitation** 

- [x] Metre en place une App-modal afin de pouvoir créer un nouveau type d'habilitation

Données à créer : 
- Label 

Le type d’habilitation est son intitulé (ex : annonceur sentinelle), il regroupe quelques informations tel que le type et la méthode. 
Table : mkg_characteristic
-  Renommer les champs renvoyés pour « faire croire » qu’elle ne sert qu’aux habilitations.

Possiblité de selectionner une methode :
- Lister les methodes avec un select
Table : mkb_characteristic__method

Possiblité de selectionner une procedure :
- Lister les procedure avec un select

**Pouvoir modifier un type d’habilitation** 

- [x] Metre en place une App-modal afin de pouvoir modifier un type d'habilitation existant (Boutton <Modifier>)

Données à modifier : 
- Label 
- Lister les methodes avec un select
- Lister les procedure avec un select

**Comment by killiankopp** [comment]
POST et PATCH api/v2/habilitation/type OK

**Comment by killiankopp** [comment]
fin des routes ! @marilehoux à toi de jouer
