### ISSUE TITLE
Consulter les informations des habilitations (types)

### ISSUE THREAD

**Issue by TigrouForMatic** [pebble-solutions/App-QSE-habilitation#24]
Le but est de lister le personnel habilité, qui à été habilité, habilitable et le personnel en cours d’habilitation : 

- [x] Lister tout le personnel habilité

Ajouter des filtres : 

- [ ] Sous contrat ou non (switch sous contrat automatique) --> Front Filtres

**Après mise en place du système de procédure**

- [ ] Lister tout le personnel en cours habilité 
- [ ] Lister tout le personnel qui peut être habilité 

**Après mise en place du système de prérequis par rapport au habilitations**

- [x] Lister tout le personnel qui à été habilité(sous entendu qui ne l’ai plus)

--> Route API à créer

**Comment by killiankopp** [comment]
lister le personnel habilité
/v2/habilitation dans la branche feature-suspension en pull request actuellement

**Comment by killiankopp** [comment]
Lister tout le personnel qui à été habilité(sous entendu qui ne l’ai plus)
/v2/habilitation dans la branche feature-suspension en pull request actuellement
il faut utiliser le paramètre active pour avoir cette liste

**Comment by killiankopp** [comment]
@TigrouForMatic  Lister tout le personnel en cours habilité : à mettre dans une autre issue indépendante... ce n'est pas pour tout de suite

**Comment by killiankopp** [comment]
Sous contrat ou non (switch sous contrat automatique)
Il n'y a pas moyen de faire ça en front plutôt ? ça m'embête de créer des ponts de ce genre côté back. d'un côté tu récupères les habilitations, de l'autre les contrats et tu fais la comparaison dans le store ?! Qu'en pensez-vous ? @TigrouForMatic @Guillaume35

**Comment by killiankopp** [comment]
Lister tout le personnel qui peut être habilité
Il faut créer une issue sur le sujet. c'est trop vaste pour être traité ici
il faut même un epics pour regarouper tout ce qu'il y a à faire pour y arriver
on en reparle si tu veux
