### ISSUE TITLE
Consulter les suspensions

### ISSUE THREAD

**Issue by TigrouForMatic** [pebble-solutions/App-QSE-habilitation#27]
Créer la route API afin de récuperer toutes les suspensions avec des parametres

- Habilitations [ids]
- Personnel [ids]

- [x] Créer la route API afin de récuperer les suspensions @killiankopp 

Une suspension c'est quand un personnel c'est fait suspendre son habilitation
Causes:
- Kn avec une note I
- Probleme relever sur le terrain PAI
- Suspension automatique quand le renouvellement n'a pas été faits avant la fin de l'habilitation

Créer des listes afin de consulter les suspensions d’habilitations passées

- [x] Lister toutes les suspensions par personnel @deathtroll22 
Faire une liste de personnel et afficher une vue avec :
- Toutes les habilitations sur lesquelles ils est suspendu (ou a été suspendu)

Prévoir l'affichage : 
- Des raisons

- [x] Lister toutes les suspensions par habilitation @deathtroll22 
Faire une liste des type d'habilitation et afficher une vue avec :
- Toutes les personnels suspendu (ou ont été suspendus)

**Comment by killiankopp** [comment]
premières routes OK !
créer, modifier, supprimer
lister
reste à gérer l'impossibilité de créer une suspension si une autre est déjà en cours

**Comment by TigrouForMatic** [comment]
@killiankopp peux-tu rajouter sur skit1

- [ ] La route personnelSuspendu qui renvoie uniquement le personnel avec qui à au moins une suspension
- [ ] Ajouter des nouvelles suspension (esitmer 15  dont 3 suspension sur le meme personnel

**Comment by TigrouForMatic** [comment]
@killiankopp peux-tu rajouter sur skit1

- [ ] La route habilitationSuspendu qui renvoie uniquement le type d'habilitation ave au moins un personnel suspension
- [ ] Le tableau de type d'habilitation doit renvoyé pour chaque habilitation le nombre de personnel suspendu, de suspention attribué

**Comment by deathtroll22** [comment]
j'attends les nouvelles routes pour finaliser
