### ISSUE TITLE
Incoherence de période d'habilitation

### ISSUE THREAD

**Issue by TigrouForMatic** [pebble-solutions/App-QSE-habilitation#40]
**Problème : Incohérence de période d'habilitation**

**Description :** Actuellement, lorsqu'un membre du personnel reçoit une habilitation, sa période d'habilitation est fixée à une durée de 3 ans, moins un jour.

**Circonstances :** Cependant, il a été constaté que certaines habilitations sont encore configurées avec une période d'habilitation basée sur une durée de 3 ans.

**Solutions envisagées :**
- [x] Établir une liste des habilitations ayant une période de 3 ans.
- [x] Corriger ces habilitations en ajustant leur durée à 3 ans, moins 1 jour.

**Comment by killiankopp** [comment]
fait dans un autre dépôt
https://github.com/pebble-solutions/DG-groupejo/tree/main/FE/incherence%20dur%C3%A9e%20habilitation
je ne corrige pas la liste pour le moment car cela implique de relancer la génération des cartes d'habilitation 
il faut avant que la carete d'habilitation dématérialisée soit en place pour le faire
il y a d'autres incohérences dans le fichier transmis à Soizic ce jour notamment des écarts de plus de 1 jour à voir comment cela est possible.

**Comment by killiankopp** [comment]
les nouvelles cartes d'habilitations étant en place, j'ai corrigé les dates d'habilitations incohérentes dans la base de données.
il reste quelques habilitations dont la date n'est pas à +/- 10 J que je n'ai pas modifié n'ayant pas eu de retour de Soizic à ce sujet
le listing a été transmis et se trouve dans le dossier cité plus haut
