### ISSUE TITLE
Incohérences entre habilitations et 1er KN

### ISSUE THREAD

**Issue by TigrouForMatic** [pebble-solutions/App-QSE-habilitation#42]
**Problème : Incohérence entre habilitations et 1er KN**

**Description :** À l'heure actuelle, il y a un problème de cohérence lorsqu'un membre du personnel confirme un contrôle de connaissance (KN) d'habilitation. L'habilitation débute dès que ce contrôle est validé, cependant, il arrive que la date de début de l'habilitation ne corresponde pas à la date de début du KN d'habilitation.

**Circonstances :** Nous avons observé des cas où certaines habilitations possèdent une date de début différente de la date du contrôle du premier KN d'habilitation.

**Solutions envisagées :**
- [x] Établir une liste des habilitations ayant une date de début (date "bb") qui diffère de la date de début du KN d'habilitation lié (date_start).
- [ ] Corriger ces habilitations en ajustant leur date de début pour qu'elle corresponde à la date_start du KN d'habilitation concerné.

**Comment by killiankopp** [comment]
la liste est établie et envoyée à Soizic le 31.08.2023
les données sont sur un autre dépôt
https://github.com/pebble-solutions/DG-groupejo/tree/main/FE/coherence%201er%20KN%20-%20habilitation
je ne corrige pas car je ne peux pas prendre la décision de ce qui est à faire
nous pourrions ajouter un outil de contrôle de cohérence (plus tard)
