### ISSUE TITLE
FIS : Statistiques

### ISSUE THREAD

**Issue by TigrouForMatic** [pebble-solutions/App-QSE-habilitation#59]
**Ajout de Statistiques dans la Vue "Fiche Individuelle de Suivi" (FIS)**

**Description :**
Cette tâche consiste à ajouter des statistiques dans l'application Habilitation. Les statistiques incluront le nombre de fois où chaque élément, tel que les questions du KN ou les équipements de protection individuelle (EPI), a été utilisé.

**Tâches Associées :**

- [x] Ajouter des statistiques pour enregistrer combien de fois chaque item, telles que les questions du KN, a été utilisé.

- [x] Mettre en place une route spécifique : "/v2/information-groupe/:id/stats", pour que les statistiques soient accessibles aux utilisateurs.

- [x] Tester les statistiques pour s'assurer qu'elles enregistrent de manière précise l'utilisation de chaque item.

- [x] Intégrer ces nouvelles statistiques à la vue "Fiche Individuelle de Suivi" (FIS) de manière à ce qu'elles soient facilement consultables par les utilisateurs.

- [x] Mettre à jour la documentation pour informer les utilisateurs de l'ajout de cette fonctionnalité de statistiques.

**Critères d'Acceptation :**

- Les statistiques sont ajoutées avec succès à l'application Habilitation.

- Les statistiques enregistrent de manière précise l'utilisation de chaque item.

- Les utilisateurs peuvent accéder facilement aux statistiques via la route spécifiée ("/v2/information-groupe/:id/stats").

- La documentation utilisateur est mise à jour pour inclure des informations sur les nouvelles statistiques.

Cette issue vise à améliorer l'application en ajoutant des statistiques utiles qui permettront aux utilisateurs de suivre l'utilisation des éléments tels que les questions du KN dans la vue "Fiche Individuelle de Suivi" (FIS).

- [x] Créer une nouvelle route fonctionnelle : @killiankopp 

--> v2/habilitation/:idHabilitation/stats 

Cette route renvoie le total de S,A,M,I en fonction des reponses des items de collecte de toute l'habilitation.

**Comment by killiankopp** [comment]
Je me lance sur ça : v2/habilitation/:idHabilitation/stats
